[package]
name = "aoc-2023-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
regex = "1.10.2"

[[bin]]
name = "1"
path = "src/day1.rs"

[[bin]]
name = "2"
path = "src/day2.rs"
